#!/usr/bin/env ruby

puts ENV['PLUGIN']

if ENV['PLUGIN'] == 'certonly'
    dry_run = '--dry-run' if ENV['TEST'] == 'true'
    domains = ENV['DOMAINS'].split.map { |d| "-d #{d}" }.join(' ')
    cmd = "certbot certonly --manual-public-ip-logging-ok #{dry_run} --agree-tos --email #{ENV['EMAIL']} --renew-by-default #{domains} --no-bootstrap --manual --manual-auth-hook /opt/certboot-hooks/#{ENV['PROVIDER']}_auth_hook.rb --manual-cleanup-hook /opt/certboot-hooks/#{ENV['PROVIDER']}_cleanup_hook.rb --preferred-challenges dns-01 --server https://acme-v02.api.letsencrypt.org/directory"
    puts cmd
    IO.popen(cmd) { |o|
        puts o.gets
    }
end